version: 1.0.0

sites:
    Baidu:
      url: https://www.baidu.com/s?wd=%s
      con: baidu.ico

    Bing:
      url: https://www.bing.com/search?q=%s
      icon: Bing-128.png

    DuckDuckGo:
      url: https://duckduckgo.com/?q=%s
      icon: duckduckgo.png

    Google:
      url: https://encrypted.google.com/search?q=%s
      icon: google-favicon-128.png

    Qwant:
      url: https://www.qwant.com/?q=%s&t=all
      icon: qwant.png

    Twitter:
      url: https://twitter.com/search?q=%s
      icon: twitter.png

    Yahoo:
      url: https://search.yahoo.com/search?p=%s
      icon: Yahoo.png

    WolframAlpha:
      url: https://www.wolframalpha.com/input/?i=%s
      icon: wolframalpha.png

    Bing Maps:
      url: https://www.bing.com/mapspreview?q=%s
      icon: bingmaps.png

    Google Maps:
      url: https://maps.google.com/?q=%s
      icon: Google-Maps-icon.png

    OpenStreetMap:
      url: https://www.openstreetmap.org/search?query=%s
      icon: Openstreetmap_logo.png

    IMDB:
      url: https://www.imdb.com/find?s=all&q=%s
      icon: imdb.png

    Metacritic:
      url: http://www.metacritic.com/search/all/%s/results
      icon: metacritic.png

    Wikipedia:
      url: https://en.wikipedia.org/wiki/Special:Search?search=%s&go=Go
      icon: wikipedia.png

    YouTube:
      url: https://www.youtube.com/results?search_query=%s
      icon: youtube.png

    Bitbucket:
      url: https://bitbucket.org/repo/all?name=%s
      icon: bitbucket-logo.png

    C++:
      url: http://en.cppreference.com/mwiki/index.php?search=%s

    CPAN:
      url: http://search.cpan.org/search?q=%s

    Git:
      url: https://git-scm.com/search/results?search=%s
      icon: git.svg

    GitHub:
      url: https://github.com/search?q=%s
      icon: github.png

    MSDN:
      # MSDN's own search engine is so bad that Google gives better results when
      # searching for specific Win32 APIs...
      url: https://encrypted.google.com/search?q=msdn+%s

    PHP:
      url: https://php.net/en/%s
      icon: php.ico

    Python3:
      url: https://docs.python.org/3/search.html?q=%s

    Python3 Mod:
      url: https://docs.python.org/3/library/%s.html

    RubyGems:
      url: https://rubygems.org/search?utf8=%E2%9C%93&query=%s


    1337x.to:
      url: http://1337x.to/sort-search/%s/seeders/desc/1/
      icon: 1337x.to.png

    SubScene:
      url: https://subscene.com/subtitles/title?q=%s&l=
      icon: subscene.png

    OpenSubtitles:
      url: https://www.opensubtitles.org/en/search2/sublanguageid-all/moviename-%s
      icon: opensubtitles.png